[project]
name = "nornir_netbox"
version = "0.3.0"
description = "Netbox plugin for Nornir"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Wim Van Deun", email = "7521270+enzzzy@users.noreply.github.com" }]
license = "Apache-2.0"
dependencies = [
    "nornir>=3.6.0",
    "requests>=2.34.2",
]
[project.entry-points."nornir.plugins.inventory"]
"NBInventory" = "nornir_netbox.plugins.inventory.netbox:NBInventory"
"NetBoxInventory2" = "nornir_netbox.plugins.inventory.netbox:NetBoxInventory2"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest",
    "pytest-coverage>=0.0",
    "requests-mock",
    "ruff>=0.15.20,<0.16",
]
docs = [
    "mkdocs>=1.6.1",
]
[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"
